version: "3.8"
services:
  spring-commerce:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=Springcommerce
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
volumes:
  db:
    driver: local
